INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @you_tube_dowinload_bot id=6441125092 - 'You Tube Bot'
INFO:aiogram.event:Update id=386115832 is not handled. Duration 6327 ms by bot id=6441125092
ERROR:aiogram.event:Cause exception while process update id=386115832 by bot id=6441125092
TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Подключение к сети было разорвано локальной системой]
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1106, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1139, in _create_connection_transport
    await waiter
  File "C:\Program Files\Python311\Lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
             ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 841, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 489, in finish_recv
    return ov.getresult()
           ^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 1236] Подключение к сети было разорвано локальной системой

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\client\session\aiohttp.py", line 167, in make_request
    async with session.post(
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiohttp\connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Подключение к сети было разорвано локальной системой]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\fsm\storage\memory.py", line 56, in lock
    yield
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\handlers\users\help.py", line 18, in bot_help
    await msg.answer("\n".join(text))
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\client\bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\Aiogram 3.0.0\.venvs\Lib\site-packages\aiogram\client\session\aiohttp.py", line 174, in make_request
    raise TelegramNetworkError(method=method, message=f"{type(e).__name__}: {e}")
aiogram.exceptions.TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Подключение к сети было разорвано локальной системой]
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Сетевая папка недоступна. За информацией о разрешении проблем в сети обратитесь к справочной системе Windows]
WARNING:aiogram.dispatcher:Sleep for 1.272115 seconds and try again... (tryings = 1, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.545118 seconds and try again... (tryings = 2, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.928996 seconds and try again... (tryings = 3, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.484559 seconds and try again... (tryings = 4, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 3.358388 seconds and try again... (tryings = 5, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.366052 seconds and try again... (tryings = 6, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.076234 seconds and try again... (tryings = 7, bot id = 6441125092)
INFO:aiogram.dispatcher:Connection established (tryings = 8, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 1236] Подключение к сети было разорвано локальной системой
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.162803 seconds and try again... (tryings = 1, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.393603 seconds and try again... (tryings = 2, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.760208 seconds and try again... (tryings = 3, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.195060 seconds and try again... (tryings = 4, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.798024 seconds and try again... (tryings = 5, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 3.482405 seconds and try again... (tryings = 6, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.518570 seconds and try again... (tryings = 7, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.037922 seconds and try again... (tryings = 8, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.865206 seconds and try again... (tryings = 9, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.921784 seconds and try again... (tryings = 10, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.129623 seconds and try again... (tryings = 11, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.014008 seconds and try again... (tryings = 12, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.057224 seconds and try again... (tryings = 13, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.921499 seconds and try again... (tryings = 14, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.965406 seconds and try again... (tryings = 15, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.002876 seconds and try again... (tryings = 16, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.047313 seconds and try again... (tryings = 17, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.080138 seconds and try again... (tryings = 18, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.131946 seconds and try again... (tryings = 19, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.119100 seconds and try again... (tryings = 20, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.736982 seconds and try again... (tryings = 21, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.017501 seconds and try again... (tryings = 22, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.013341 seconds and try again... (tryings = 23, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.903719 seconds and try again... (tryings = 24, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.907166 seconds and try again... (tryings = 25, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.113536 seconds and try again... (tryings = 26, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.063578 seconds and try again... (tryings = 27, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.805663 seconds and try again... (tryings = 28, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.833671 seconds and try again... (tryings = 29, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.833364 seconds and try again... (tryings = 30, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.888354 seconds and try again... (tryings = 31, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.818097 seconds and try again... (tryings = 32, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.123230 seconds and try again... (tryings = 33, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.077398 seconds and try again... (tryings = 34, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.102547 seconds and try again... (tryings = 35, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.147303 seconds and try again... (tryings = 36, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.889678 seconds and try again... (tryings = 37, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.059175 seconds and try again... (tryings = 38, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.049637 seconds and try again... (tryings = 39, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.266300 seconds and try again... (tryings = 40, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.027061 seconds and try again... (tryings = 41, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.976040 seconds and try again... (tryings = 42, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.000326 seconds and try again... (tryings = 43, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.141908 seconds and try again... (tryings = 44, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.956784 seconds and try again... (tryings = 45, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.900115 seconds and try again... (tryings = 46, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.953021 seconds and try again... (tryings = 47, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.959123 seconds and try again... (tryings = 48, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.150083 seconds and try again... (tryings = 49, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.096058 seconds and try again... (tryings = 50, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.137005 seconds and try again... (tryings = 51, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.991707 seconds and try again... (tryings = 52, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.102432 seconds and try again... (tryings = 53, bot id = 6441125092)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.031408 seconds and try again... (tryings = 54, bot id = 6441125092)
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @you_tube_dowinload_bot id=6441125092 - 'You Tube Bot'
